/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronaldo
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    String id;
    public Cliente() {
        initComponents();
        setLocationRelativeTo(null);
        //this.uno.setSelected(true);
        this.setTitle("Cliente");  
        cerrar();
        new CambiaPanel(panelPrincipal, new HomeCliente(this));
    }
    
    public Cliente(String n, String c, String t, String id) {
        initComponents();
        setLocationRelativeTo(null);
        //this.uno.setSelected(true);
        this.setTitle("Cliente");  
        cerrar();
        this.id = id;
        new CambiaPanel(panelPrincipal, new HomeCliente(this,id));
        jLabel3.setText(n);
        jLabel5.setText(t);
        jLabel4.setText(c);        
    }

    public void cerrar(){
        try{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e){
                    confirmarSalida();
                }
            });
            this.setVisible(true);
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    public void confirmarSalida(){
        int valor = JOptionPane.showConfirmDialog(this,"No ha cerrado sesión"+
                ", ¿estás seguro de cerrar?", "Advertencia", 
                JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(valor==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null,"Gracias por su visita","Gracias",
                    JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dos = new Especial.RSButtonMetro();
        tres = new Especial.RSButtonMetro();
        cuatro = new Especial.RSButtonMetro();
        uno = new Especial.RSButtonMetro();
        rSButtonMetro6 = new Especial.RSButtonMetro();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelito = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Name.png"))); // NOI18N

        dos.setBackground(new java.awt.Color(255, 255, 255));
        dos.setForeground(new java.awt.Color(0, 0, 0));
        dos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar.png"))); // NOI18N
        dos.setText("Registrar ERU");
        dos.setColorHover(new java.awt.Color(153, 204, 255));
        dos.setColorNormal(new java.awt.Color(255, 255, 255));
        dos.setColorPressed(new java.awt.Color(255, 255, 255));
        dos.setColorTextHover(new java.awt.Color(0, 0, 0));
        dos.setColorTextNormal(new java.awt.Color(0, 0, 0));
        dos.setColorTextPressed(new java.awt.Color(0, 0, 0));
        dos.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        dos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dosMousePressed(evt);
            }
        });
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        tres.setBackground(new java.awt.Color(255, 255, 255));
        tres.setForeground(new java.awt.Color(0, 0, 0));
        tres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.png"))); // NOI18N
        tres.setText("Modificar ERU");
        tres.setColorHover(new java.awt.Color(153, 204, 255));
        tres.setColorNormal(new java.awt.Color(255, 255, 255));
        tres.setColorPressed(new java.awt.Color(255, 255, 255));
        tres.setColorTextHover(new java.awt.Color(0, 0, 0));
        tres.setColorTextNormal(new java.awt.Color(0, 0, 0));
        tres.setColorTextPressed(new java.awt.Color(0, 0, 0));
        tres.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tres.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tresMousePressed(evt);
            }
        });
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        cuatro.setBackground(new java.awt.Color(255, 255, 255));
        cuatro.setForeground(new java.awt.Color(0, 0, 0));
        cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Chat.png"))); // NOI18N
        cuatro.setText("Chat");
        cuatro.setColorHover(new java.awt.Color(153, 204, 255));
        cuatro.setColorNormal(new java.awt.Color(255, 255, 255));
        cuatro.setColorPressed(new java.awt.Color(255, 255, 255));
        cuatro.setColorTextHover(new java.awt.Color(0, 0, 0));
        cuatro.setColorTextNormal(new java.awt.Color(0, 0, 0));
        cuatro.setColorTextPressed(new java.awt.Color(0, 0, 0));
        cuatro.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cuatro.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuatroMousePressed(evt);
            }
        });
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        uno.setForeground(new java.awt.Color(0, 0, 0));
        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Home.png"))); // NOI18N
        uno.setText("Home");
        uno.setBorderPainted(false);
        uno.setColorHover(new java.awt.Color(153, 204, 255));
        uno.setColorNormal(new java.awt.Color(255, 255, 255));
        uno.setColorPressed(new java.awt.Color(255, 255, 255));
        uno.setColorTextHover(new java.awt.Color(51, 51, 51));
        uno.setColorTextNormal(new java.awt.Color(0, 0, 0));
        uno.setColorTextPressed(new java.awt.Color(0, 0, 0));
        uno.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        uno.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                unoMousePressed(evt);
            }
        });
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        rSButtonMetro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogOut.png"))); // NOI18N
        rSButtonMetro6.setText("Salir");
        rSButtonMetro6.setColorHover(new java.awt.Color(153, 204, 255));
        rSButtonMetro6.setColorNormal(new java.awt.Color(255, 255, 255));
        rSButtonMetro6.setColorPressed(new java.awt.Color(255, 255, 255));
        rSButtonMetro6.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButtonMetro6.setColorTextNormal(new java.awt.Color(0, 0, 0));
        rSButtonMetro6.setColorTextPressed(new java.awt.Color(0, 0, 0));
        rSButtonMetro6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rSButtonMetro6.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButtonMetro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro6ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Photo.png"))); // NOI18N

        jLabel3.setText(" ");

        jLabel4.setText(" ");

        jLabel5.setText(" ");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cuatro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                        .addComponent(dos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSButtonMetro6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(rSButtonMetro6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 240, 560));

        panelito.setBackground(new java.awt.Color(255, 153, 51));
        panelito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelito.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        getContentPane().add(panelito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1077, 50));

        panelPrincipal.setLayout(new javax.swing.BoxLayout(panelPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 840, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        // TODO add your handling code here:
        /*x.setVisible(true);
        x.chat();*/
        /*Chat a = new Chat(this,false);
        a.setVisible(true);
        a.chat();*/
       /* if (this.uno.isSelected()){
            this.uno.setColorNormal(new Color(255,255,255));            
            this.uno.setColorHover(new Color(255,255,255));            
            this.uno.setColorPressed(new Color(255,255,255));            
            
            this.dos.setColorNormal(new Color(255,255,255));            
            this.dos.setColorHover(new Color(255,255,255));            
            this.dos.setColorPressed(new Color(255,255,255));    
            
            this.tres.setColorNormal(new Color(255,255,255));            
            this.tres.setColorHover(new Color(255,255,255));            
            this.tres.setColorPressed(new Color(255,255,255)); 
            
            this.cuatro.setColorNormal(new Color(153,204,255));            
            this.cuatro.setColorHover(new Color(255,255,255));            
            this.cuatro.setColorPressed(new Color(255,255,255)); 
        }else{
            this.cuatro.setColorNormal(new Color(255,255,255));            
            this.cuatro.setColorHover(new Color(255,255,255));            
            this.cuatro.setColorPressed(new Color(255,255,255));  
        }    */      
    }//GEN-LAST:event_cuatroActionPerformed

    private void rSButtonMetro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Gracias por su visita","Gracias",
                JOptionPane.INFORMATION_MESSAGE);        
        Login x = new Login();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonMetro6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int posicion = this.panelMenu.getX();
        if(posicion>-1){
            Animacion.Animacion.mover_izquierda(0, -240, 2, 2, panelMenu);
            Animacion.Animacion.mover_izquierda(240, 120, 2, 2, panelPrincipal);            
        }else{
            Animacion.Animacion.mover_derecha(-240, 0, 2, 2, panelMenu);
            Animacion.Animacion.mover_derecha(120, 240, 2, 2, panelPrincipal);
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(panelPrincipal,new HomeCliente(this,id));
        /*if (this.uno.isSelected()){
            this.uno.setColorNormal(new Color(153,204,255));            
            this.uno.setColorHover(new Color(255,255,255));            
            this.uno.setColorPressed(new Color(255,255,255));            
            
            this.dos.setColorNormal(new Color(255,255,255));            
            this.dos.setColorHover(new Color(255,255,255));            
            this.dos.setColorPressed(new Color(255,255,255));    
            
            this.tres.setColorNormal(new Color(255,255,255));            
            this.tres.setColorHover(new Color(255,255,255));            
            this.tres.setColorPressed(new Color(255,255,255)); 
            
            this.cuatro.setColorNormal(new Color(255,255,255));            
            this.cuatro.setColorHover(new Color(255,255,255));            
            this.cuatro.setColorPressed(new Color(255,255,255)); 
        }else{
            this.uno.setColorNormal(new Color(255,255,255));            
            this.uno.setColorHover(new Color(255,255,255));            
            this.uno.setColorPressed(new Color(255,255,255));  
        }*/
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(panelPrincipal,new RegistrarEru(panelPrincipal,this));
        /*if (this.uno.isSelected()){
            this.uno.setColorNormal(new Color(255,255,255));            
            this.uno.setColorHover(new Color(255,255,255));            
            this.uno.setColorPressed(new Color(255,255,255));            
            
            this.dos.setColorNormal(new Color(153,204,255));            
            this.dos.setColorHover(new Color(255,255,255));            
            this.dos.setColorPressed(new Color(255,255,255));    
            
            this.tres.setColorNormal(new Color(255,255,255));            
            this.tres.setColorHover(new Color(255,255,255));            
            this.tres.setColorPressed(new Color(255,255,255)); 
            
            this.cuatro.setColorNormal(new Color(255,255,255));            
            this.cuatro.setColorHover(new Color(255,255,255));            
            this.cuatro.setColorPressed(new Color(255,255,255)); 
        }else{
            this.uno.setColorNormal(new Color(255,255,255));            
            this.uno.setColorHover(new Color(255,255,255));            
            this.uno.setColorPressed(new Color(255,255,255));  
        }  */
    }//GEN-LAST:event_dosActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(panelPrincipal,new ModificarEru(this,panelPrincipal,id));
        /*if (this.uno.isSelected()){
            this.uno.setColorNormal(new Color(255,255,255));            
            this.uno.setColorHover(new Color(255,255,255));            
            this.uno.setColorPressed(new Color(255,255,255));            
            
            this.dos.setColorNormal(new Color(255,255,255));            
            this.dos.setColorHover(new Color(255,255,255));            
            this.dos.setColorPressed(new Color(255,255,255));    
            
            this.tres.setColorNormal(new Color(153,204,255));            
            this.tres.setColorHover(new Color(255,255,255));            
            this.tres.setColorPressed(new Color(255,255,255)); 
            
            this.cuatro.setColorNormal(new Color(255,255,255));            
            this.cuatro.setColorHover(new Color(255,255,255));            
            this.cuatro.setColorPressed(new Color(255,255,255)); 
        }else{
            this.tres.setColorNormal(new Color(255,255,255));            
            this.tres.setColorHover(new Color(255,255,255));            
            this.tres.setColorPressed(new Color(255,255,255));  
        }      */    
    }//GEN-LAST:event_tresActionPerformed

    private void unoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unoMousePressed
        // TODO add your handling code here:
        this.uno.setSelected(true);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);
    }//GEN-LAST:event_unoMousePressed

    private void dosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosMousePressed
        // TODO add your handling code here:
        this.uno.setSelected(false);
        this.dos.setSelected(true);
        this.tres.setSelected(false);
        this.cuatro.setSelected(false);        
    }//GEN-LAST:event_dosMousePressed

    private void tresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMousePressed
        // TODO add your handling code here:
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(true);
        this.cuatro.setSelected(false);        
    }//GEN-LAST:event_tresMousePressed

    private void cuatroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroMousePressed
        // TODO add your handling code here:
        this.uno.setSelected(false);
        this.dos.setSelected(false);
        this.tres.setSelected(false);
        this.cuatro.setSelected(true);        
    }//GEN-LAST:event_cuatroMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Especial.RSButtonMetro cuatro;
    private Especial.RSButtonMetro dos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelito;
    private Especial.RSButtonMetro rSButtonMetro6;
    private Especial.RSButtonMetro tres;
    private Especial.RSButtonMetro uno;
    // End of variables declaration//GEN-END:variables
}
