/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import LogicaNegocio.ClienteBL;
import Modelo.Proyecto;
import Modelo.Requerimiento;
import Modelo.TipoRequerimiento;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ronaldo
 */
public class ModificarEru extends javax.swing.JPanel {

    /**
     * Creates new form ModificarEru
     */
    DefaultTableModel modelo = new DefaultTableModel();    
    Cliente x;
    JPanel panelPrincipal;
    String id;
    private Proyecto proy;
    private ClienteBL clientebl;
    private Cliente objseleccionado;

    public Cliente getObjseleccionado() {
        return objseleccionado;
    }

    public void setObjseleccionado(Cliente objseleccionado) {
        this.objseleccionado = objseleccionado;
    }
    public ModificarEru() {
        initComponents();
    }
    
    public ModificarEru(Cliente c,JPanel d,String id){
        initComponents();
        x = c;
        panelPrincipal = d;
        this.id = id;
        clientebl=new ClienteBL();
        
        ArrayList<String> e1 = new ArrayList<String>();
            e1 = clientebl.listaTipoRequerimiento();
            for (int i = 0; i < e1.size(); i++) {
                cboxtipoRequerimientoModificar.addItem(e1.get(i));
                //System.out.println(e.get(i).getRazonSocial());
            }
            
            ArrayList<String> e2 = new ArrayList<String>();
            e2 = clientebl.listaPrioridad();
            for (int i = 0; i < e2.size(); i++) {
                cboxprioridadmodificar.addItem(e2.get(i));
                //System.out.println(e.get(i).getRazonSocial());
            }
            
        modelo.addColumn("Requerimiento");
        modelo.addColumn("Prioridad");
        modelo.addColumn("Tipo Requerimiento");
        tablaErusmodificar.setModel(modelo);            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloModificar = new javax.swing.JLabel();
        lblNomProyectoModificar = new javax.swing.JLabel();
        txtnomproyModificar = new javax.swing.JTextField();
        btnListoModificar = new javax.swing.JButton();
        btnBuscarModificar = new javax.swing.JButton();
        lblObjetivoReqModificar = new javax.swing.JLabel();
        txtobjetivomodificar = new javax.swing.JTextField();
        lblFechaModificar = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaErusmodificar = new javax.swing.JTable();
        lblRequerimientoModificar = new javax.swing.JLabel();
        txtrequerimientomodificar = new javax.swing.JTextField();
        lblPrioridadModificar = new javax.swing.JLabel();
        cboxprioridadmodificar = new javax.swing.JComboBox<>();
        btnAgregarmod = new javax.swing.JButton();
        btnmodificarmod = new javax.swing.JButton();
        btnEliminarmod = new javax.swing.JButton();
        lbl100modificar = new javax.swing.JLabel();
        jdatemodificar = new com.toedter.calendar.JDateChooser();
        jPanelProyectModificar = new javax.swing.JPanel();
        lbltipoReqModificar = new javax.swing.JLabel();
        cboxtipoRequerimientoModificar = new javax.swing.JComboBox<>();
        jPanelRequerimientoModificar = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloModificar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTituloModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloModificar.setText("Modificar Requerimiento de Usuario");
        add(lblTituloModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 26, 634, 39));

        lblNomProyectoModificar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNomProyectoModificar.setText("Nombre del Proyecto:");
        add(lblNomProyectoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 120, 175, 30));

        txtnomproyModificar.setEditable(false);
        add(txtnomproyModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 120, 207, -1));

        btnListoModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Yes.png"))); // NOI18N
        btnListoModificar.setBorderPainted(false);
        btnListoModificar.setContentAreaFilled(false);
        btnListoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoModificarActionPerformed(evt);
            }
        });
        add(btnListoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 195, 53));

        btnBuscarModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btnBuscarModificar.setBorderPainted(false);
        btnBuscarModificar.setContentAreaFilled(false);
        btnBuscarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarModificarActionPerformed(evt);
            }
        });
        add(btnBuscarModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, 30));

        lblObjetivoReqModificar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblObjetivoReqModificar.setText("Objetivo del Requerimiento:");
        add(lblObjetivoReqModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 151, -1, -1));

        txtobjetivomodificar.setEditable(false);
        add(txtobjetivomodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 150, 207, -1));

        lblFechaModificar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFechaModificar.setText("Fecha Estimada:");
        add(lblFechaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        tablaErusmodificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaErusmodificar);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 690, 140));

        lblRequerimientoModificar.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lblRequerimientoModificar.setText("Requerimiento:");
        add(lblRequerimientoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        txtrequerimientomodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrequerimientomodificarActionPerformed(evt);
            }
        });
        add(txtrequerimientomodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 430, -1));

        lblPrioridadModificar.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lblPrioridadModificar.setText("Prioridad:");
        add(lblPrioridadModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        cboxprioridadmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxprioridadmodificarActionPerformed(evt);
            }
        });
        add(cboxprioridadmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        btnAgregarmod.setText("Agregar");
        btnAgregarmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarmodActionPerformed(evt);
            }
        });
        add(btnAgregarmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 90, -1));

        btnmodificarmod.setText("Modificar");
        btnmodificarmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarmodActionPerformed(evt);
            }
        });
        add(btnmodificarmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 90, -1));

        btnEliminarmod.setText("Eliminar");
        btnEliminarmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarmodActionPerformed(evt);
            }
        });
        add(btnEliminarmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 90, -1));

        lbl100modificar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lbl100modificar.setText("[100 caracteres]");
        add(lbl100modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));
        add(jdatemodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 200, -1));

        jPanelProyectModificar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Generales del Proyecto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 11))); // NOI18N
        add(jPanelProyectModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 700, 130));

        lbltipoReqModificar.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lbltipoReqModificar.setText("Tipo Requerimiento:");
        add(lbltipoReqModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        add(cboxtipoRequerimientoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 140, -1));

        jPanelRequerimientoModificar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Descripción de Requerimientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 11))); // NOI18N
        add(jPanelRequerimientoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 610, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoModificarActionPerformed
        // TODO add your handling code here:
        String rpta = "¿Estás seguro?";
        if(JOptionPane.showConfirmDialog(null, rpta,
                "ADVERTENCIA",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null,"Modificación exitosa");
        }            
        new CambiaPanel(panelPrincipal, new HomeCliente());
    }//GEN-LAST:event_btnListoModificarActionPerformed

    private void btnBuscarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarModificarActionPerformed
        // TODO add your handling code here:
        //new BuscarEruCliente(x,true,id).setVisible(true);
        BuscarEruCliente frm = new BuscarEruCliente(x,true,id);
        frm.setVisible(true);
        proy = frm.proy;
        txtnomproyModificar.setText(proy.getNombre());
        txtobjetivomodificar.setText(proy.getEru().getObj().getDescripcion());
       
        Requerimiento req;
        
        ArrayList<Requerimiento>lReq=proy.getEru().getListaRequerimiento();
        for (int i=0;i<lReq.size();i++){
            String Dato[] = new String[3];
            Dato[0] = lReq.get(i).getDescripcion();
            if(lReq.get(i).getPrioridad()==1)Dato[1]="BAJA";
            if(lReq.get(i).getPrioridad()==2)Dato[1]="MEDIA";
            if(lReq.get(i).getPrioridad()==3)Dato[1]="ALTA";
            
            if(lReq.get(i).getTipo()==TipoRequerimiento.FUNCIONAL)Dato[2]="FUNCIONAL";
            if(lReq.get(i).getTipo()==TipoRequerimiento.NO_FUNCIONAL)Dato[2]="NO_FUNCIONAL";
            
            modelo.addRow(Dato);
        }
    }//GEN-LAST:event_btnBuscarModificarActionPerformed

    private void txtrequerimientomodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrequerimientomodificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrequerimientomodificarActionPerformed

    private void cboxprioridadmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxprioridadmodificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxprioridadmodificarActionPerformed

    private void btnEliminarmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarmodActionPerformed
        // TODO add your handling code here:
        int FilaSelec = tablaErusmodificar.getSelectedRow();
        if(FilaSelec>=0){
            modelo.removeRow(FilaSelec);
        }else{
            JOptionPane.showMessageDialog(this, "Fila No Seleccionada");
        }        
    }//GEN-LAST:event_btnEliminarmodActionPerformed

    private void btnAgregarmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarmodActionPerformed
        // TODO add your handling code here:
        Requerimiento req;
        String Dato[] = new String[3];
        Dato[0] = txtrequerimientomodificar.getText();
        Dato[1] = (String)cboxprioridadmodificar.getSelectedItem();
        Dato[2] = (String)cboxtipoRequerimientoModificar.getSelectedItem();
        modelo.addRow(Dato);
        txtrequerimientomodificar.setText("");
        cboxprioridadmodificar.setSelectedIndex(-1);
        cboxtipoRequerimientoModificar.setSelectedIndex(-1);        
    }//GEN-LAST:event_btnAgregarmodActionPerformed

    private void btnmodificarmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarmodActionPerformed
        // TODO add your handling code here:
        int FilaSelec = tablaErusmodificar.getSelectedRow();
        if(FilaSelec >= 0){
            txtrequerimientomodificar.setText(tablaErusmodificar.getValueAt(FilaSelec,0).toString());
            cboxprioridadmodificar.setSelectedItem(tablaErusmodificar.getValueAt(FilaSelec, 1).toString());
            cboxtipoRequerimientoModificar.setSelectedItem(tablaErusmodificar.getValueAt(FilaSelec, 2).toString());
            
            modelo.removeRow(FilaSelec);
        }else{
            JOptionPane.showMessageDialog(this, "Fila No Seleccionada");
        }
        
    }//GEN-LAST:event_btnmodificarmodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarmod;
    private javax.swing.JButton btnBuscarModificar;
    private javax.swing.JButton btnEliminarmod;
    private javax.swing.JButton btnListoModificar;
    private javax.swing.JButton btnmodificarmod;
    private javax.swing.JComboBox<String> cboxprioridadmodificar;
    private javax.swing.JComboBox<String> cboxtipoRequerimientoModificar;
    private javax.swing.JPanel jPanelProyectModificar;
    private javax.swing.JPanel jPanelRequerimientoModificar;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdatemodificar;
    private javax.swing.JLabel lbl100modificar;
    private javax.swing.JLabel lblFechaModificar;
    private javax.swing.JLabel lblNomProyectoModificar;
    private javax.swing.JLabel lblObjetivoReqModificar;
    private javax.swing.JLabel lblPrioridadModificar;
    private javax.swing.JLabel lblRequerimientoModificar;
    private javax.swing.JLabel lblTituloModificar;
    private javax.swing.JLabel lbltipoReqModificar;
    private javax.swing.JTable tablaErusmodificar;
    private javax.swing.JTextField txtnomproyModificar;
    private javax.swing.JTextField txtobjetivomodificar;
    private javax.swing.JTextField txtrequerimientomodificar;
    // End of variables declaration//GEN-END:variables
}
