/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import LogicaNegocio.ClienteBL;
import Modelo.Empresa;
import Modelo.Eru;
import Modelo.Objetivo;
import Modelo.Proyecto;
import Modelo.Requerimiento;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ronaldo
 */
public class RegistrarEru extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarEru
     */
    private ClienteBL clientebl;
    JPanel panelPrincipal;
    Cliente cliente;
    public RegistrarEru()  {
        initComponents();
        clientebl=new ClienteBL();
        try{
            
            ArrayList<Objetivo> o = new ArrayList<Objetivo>();
            o = clientebl.listaobjetivos();
            for (int i = 0; i < o.size(); i++) {
                cboxObjetivos.addItem(o.get(i).getDescripcion());
                //System.out.println(o.get(i).getDescripcion());
            }
            
            ArrayList<Empresa> e = new ArrayList<Empresa>();
            e = clientebl.listarEmpresa();
            for (int i = 0; i < e.size(); i++) {
                cboxEmpresa.addItem(e.get(i).getRazonSocial());
                //System.out.println(e.get(i).getRazonSocial());
            }
        }catch(Exception ex){
        
        }        
    }
    
    public RegistrarEru(JPanel c,Cliente cliente)  {
        initComponents();
        this.cliente = cliente;
        clientebl=new ClienteBL();
        panelPrincipal = c;
        try{
            
            ArrayList<Objetivo> o = new ArrayList<Objetivo>();
            o = clientebl.listaobjetivos();
            for (int i = 0; i < o.size(); i++) {
                cboxObjetivos.addItem(o.get(i).getDescripcion());
                //System.out.println(o.get(i).getDescripcion());
            }
            
            ArrayList<Empresa> e = new ArrayList<Empresa>();
            e = clientebl.listarEmpresa();
            for (int i = 0; i < e.size(); i++) {
                cboxEmpresa.addItem(e.get(i).getRazonSocial());
                //System.out.println(e.get(i).getRazonSocial());
            }
        }catch(Exception ex){
        
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomProyecto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnListo = new javax.swing.JButton();
        cboxEmpresa = new javax.swing.JComboBox<>();
        cboxObjetivos = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaErus = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtrequerimiento = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        cboxprioridad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Especificación de Requerimiento de Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 27, 634, 39));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Datos Generales del Proyecto");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 231, 31));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nombre del Proyecto:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 115, 151, 26));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Empresa/Negocios:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 151, 26));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Objetivo del Requerimiento:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 180, 31));

        txtNomProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomProyectoActionPerformed(evt);
            }
        });
        add(txtNomProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 115, 310, 26));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Descripción de los Requerimientos");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 31));

        btnListo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Send.png"))); // NOI18N
        btnListo.setBorderPainted(false);
        btnListo.setContentAreaFilled(false);
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });
        add(btnListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 149, 46));

        add(cboxEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 310, -1));

        cboxObjetivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxObjetivosActionPerformed(evt);
            }
        });
        add(cboxObjetivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 310, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Fecha Estimada:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        tablaErus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Requerimiento", "Prioridad"
            }
        ));
        jScrollPane3.setViewportView(tablaErus);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 680, 140));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel9.setText("Requerimiento:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        txtrequerimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrequerimientoActionPerformed(evt);
            }
        });
        add(txtrequerimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 430, -1));

        btnAgregar.setText("Agregar");
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        cboxprioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cboxprioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxprioridadActionPerformed(evt);
            }
        });
        add(cboxprioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel8.setText("Prioridad:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        btnEliminar.setText("Eliminar");
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel10.setText("[100 caracteres]");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // TODO add your handling code here:
        String rpta = "¿Estás seguro?";
        if(JOptionPane.showConfirmDialog(null, rpta,"ADVERTENCIA",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            
            //REGISTRAR

            Eru e=new Eru();

            Proyecto p=new Proyecto();
            Requerimiento req=new Requerimiento();
            String r=txtNomProyecto.getText();
            //nombre
            p.setNombre(r);
            e.setProyecto(p);
            
            //nombre empresa
            //String n=txtNomEmpresa.getText();
            //String a=txtAreaRequ.getText();
            
            int id=e.getIdERU();
            //req.setEru(id);
            //req.setDescripcion(a);
            e.setRequerimiento(req);
            
            
            clientebl.RegistrarEru(e);
            JOptionPane.showMessageDialog(null,"Se envió correctamente");
            new CambiaPanel(panelPrincipal,new HomeCliente(cliente));
        }     
                 
    }//GEN-LAST:event_btnListoActionPerformed

    private void cboxObjetivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxObjetivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxObjetivosActionPerformed

    private void txtrequerimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrequerimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrequerimientoActionPerformed

    private void cboxprioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxprioridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxprioridadActionPerformed

    private void txtNomProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomProyectoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtNomProyectoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListo;
    private javax.swing.JComboBox<String> cboxEmpresa;
    private javax.swing.JComboBox<String> cboxObjetivos;
    private javax.swing.JComboBox<String> cboxprioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaErus;
    private javax.swing.JTextField txtNomProyecto;
    private javax.swing.JTextField txtrequerimiento;
    // End of variables declaration//GEN-END:variables
}
