/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import LogicaNegocio.ClienteBL;
import Modelo.Empresa;
import Modelo.Eru;
import Modelo.Objetivo;
import Modelo.Proyecto;
import Modelo.Requerimiento;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ronaldo
 */
public class RegistrarEru extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarEru
     */
    private ClienteBL clientebl;
    JPanel panelPrincipal;
    Cliente cliente;
    public RegistrarEru()  {
        initComponents();
        clientebl=new ClienteBL();
        try{
            
            ArrayList<Objetivo> o = new ArrayList<Objetivo>();
            o = clientebl.listaobjetivos();
            for (int i = 0; i < o.size(); i++) {
                cboxObjetivos.addItem(o.get(i).getDescripcion());
                //System.out.println(o.get(i).getDescripcion());
            }
            
            ArrayList<Empresa> e = new ArrayList<Empresa>();
            e = clientebl.listarEmpresa();
            for (int i = 0; i < e.size(); i++) {
                cboxEmpresa.addItem(e.get(i).getRazonSocial());
                //System.out.println(e.get(i).getRazonSocial());
            }
        }catch(Exception ex){
        
        }        
    }
    
    public RegistrarEru(JPanel c,Cliente cliente)  {
        initComponents();
        this.cliente = cliente;
        clientebl=new ClienteBL();
        panelPrincipal = c;
        try{
            
            ArrayList<Objetivo> o = new ArrayList<Objetivo>();
            o = clientebl.listaobjetivos();
            for (int i = 0; i < o.size(); i++) {
                cboxObjetivos.addItem(o.get(i).getDescripcion());
                //System.out.println(o.get(i).getDescripcion());
            }
            
            ArrayList<Empresa> e = new ArrayList<Empresa>();
            e = clientebl.listarEmpresa();
            for (int i = 0; i < e.size(); i++) {
                cboxEmpresa.addItem(e.get(i).getRazonSocial());
                //System.out.println(e.get(i).getRazonSocial());
            }
        }catch(Exception ex){
        
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloRegistrar = new javax.swing.JLabel();
        lblnomproyReg = new javax.swing.JLabel();
        lblNomEmpRegistrar = new javax.swing.JLabel();
        lblObjReqRegistrar = new javax.swing.JLabel();
        txtNomProyecto = new javax.swing.JTextField();
        btnListo = new javax.swing.JButton();
        cboxEmpresa = new javax.swing.JComboBox<>();
        cboxObjetivos = new javax.swing.JComboBox<>();
        lblFechaRegistrar = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaErusRegistrar = new javax.swing.JTable();
        lblReqRegistrar = new javax.swing.JLabel();
        txtrequerimiento = new javax.swing.JTextField();
        btnAgregarReg = new javax.swing.JButton();
        cboxprioridad = new javax.swing.JComboBox<>();
        lblPrioridadRegistrar = new javax.swing.JLabel();
        btnEliminarReg = new javax.swing.JButton();
        lbl100regustrar = new javax.swing.JLabel();
        jDateFechaRegistrar = new com.toedter.calendar.JDateChooser();
        jpanelProyRegistrar = new javax.swing.JPanel();
        cboxtipoRequerimientoRegistrar = new javax.swing.JComboBox<>();
        lblTipoReqReguistrat = new javax.swing.JLabel();
        jPanelRequerimientoModificar = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloRegistrar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTituloRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRegistrar.setText("Registrar Especificación de Requerimiento de Usuario");
        add(lblTituloRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 634, 39));

        lblnomproyReg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblnomproyReg.setText("Nombre del Proyecto:");
        add(lblnomproyReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 115, 151, 26));

        lblNomEmpRegistrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNomEmpRegistrar.setText("Empresa/Negocios:");
        add(lblNomEmpRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 151, 26));

        lblObjReqRegistrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblObjReqRegistrar.setText("Objetivo del Requerimiento:");
        add(lblObjReqRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 180, 31));

        txtNomProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomProyectoActionPerformed(evt);
            }
        });
        add(txtNomProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 115, 310, 26));

        btnListo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Send.png"))); // NOI18N
        btnListo.setBorderPainted(false);
        btnListo.setContentAreaFilled(false);
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });
        add(btnListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 149, 46));

        add(cboxEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 310, -1));

        cboxObjetivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxObjetivosActionPerformed(evt);
            }
        });
        add(cboxObjetivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 310, -1));

        lblFechaRegistrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFechaRegistrar.setText("Fecha Estimada:");
        add(lblFechaRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        tablaErusRegistrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Requerimiento", "Prioridad"
            }
        ));
        jScrollPane3.setViewportView(tablaErusRegistrar);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 680, 140));

        lblReqRegistrar.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lblReqRegistrar.setText("Requerimiento:");
        add(lblReqRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        txtrequerimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrequerimientoActionPerformed(evt);
            }
        });
        add(txtrequerimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 430, -1));

        btnAgregarReg.setText("Agregar");
        btnAgregarReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRegActionPerformed(evt);
            }
        });
        add(btnAgregarReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        cboxprioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cboxprioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxprioridadActionPerformed(evt);
            }
        });
        add(cboxprioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        lblPrioridadRegistrar.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lblPrioridadRegistrar.setText("Prioridad:");
        add(lblPrioridadRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        btnEliminarReg.setText("Eliminar");
        add(btnEliminarReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, -1));

        lbl100regustrar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lbl100regustrar.setText("[100 caracteres]");
        add(lbl100regustrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));
        add(jDateFechaRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 310, -1));

        jpanelProyRegistrar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Generales del Proyecto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 11))); // NOI18N
        add(jpanelProyRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 700, 160));

        add(cboxtipoRequerimientoRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 140, -1));

        lblTipoReqReguistrat.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lblTipoReqReguistrat.setText("Tipo Requerimiento:");
        add(lblTipoReqReguistrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jPanelRequerimientoModificar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Descripción de Requerimientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 11))); // NOI18N
        add(jPanelRequerimientoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 610, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // TODO add your handling code here:
        String rpta = "¿Estás seguro?";
        if(JOptionPane.showConfirmDialog(null, rpta,"ADVERTENCIA",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            
            //REGISTRAR

            Eru e=new Eru();

            Proyecto p=new Proyecto();
            Requerimiento req=new Requerimiento();
            String r=txtNomProyecto.getText();
            //nombre
            p.setNombre(r);
            e.setProyecto(p);
            
            //nombre empresa
            //String n=txtNomEmpresa.getText();
            //String a=txtAreaRequ.getText();
            
            int id=e.getIdERU();
            //req.setEru(id);
            //req.setDescripcion(a);
            e.setRequerimiento(req);
            
            
            clientebl.RegistrarEru(e);
            JOptionPane.showMessageDialog(null,"Se envió correctamente");
            new CambiaPanel(panelPrincipal,new HomeCliente(cliente));
        }     
                 
    }//GEN-LAST:event_btnListoActionPerformed

    private void cboxObjetivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxObjetivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxObjetivosActionPerformed

    private void cboxprioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxprioridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxprioridadActionPerformed

    private void txtNomProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomProyectoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtNomProyectoActionPerformed

    private void txtrequerimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrequerimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrequerimientoActionPerformed

    private void btnAgregarRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarRegActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarReg;
    private javax.swing.JButton btnEliminarReg;
    private javax.swing.JButton btnListo;
    private javax.swing.JComboBox<String> cboxEmpresa;
    private javax.swing.JComboBox<String> cboxObjetivos;
    private javax.swing.JComboBox<String> cboxprioridad;
    private javax.swing.JComboBox<String> cboxtipoRequerimientoRegistrar;
    private com.toedter.calendar.JDateChooser jDateFechaRegistrar;
    private javax.swing.JPanel jPanelRequerimientoModificar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpanelProyRegistrar;
    private javax.swing.JLabel lbl100regustrar;
    private javax.swing.JLabel lblFechaRegistrar;
    private javax.swing.JLabel lblNomEmpRegistrar;
    private javax.swing.JLabel lblObjReqRegistrar;
    private javax.swing.JLabel lblPrioridadRegistrar;
    private javax.swing.JLabel lblReqRegistrar;
    private javax.swing.JLabel lblTipoReqReguistrat;
    private javax.swing.JLabel lblTituloRegistrar;
    private javax.swing.JLabel lblnomproyReg;
    private javax.swing.JTable tablaErusRegistrar;
    private javax.swing.JTextField txtNomProyecto;
    private javax.swing.JTextField txtrequerimiento;
    // End of variables declaration//GEN-END:variables
}
